// <auto-generated />
using System;
using Despachos.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Despachos.Api.Migrations
{
    [DbContext(typeof(DespachosDbContext))]
    partial class DespachosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Despachos.Api.Models.ConfirmacionDespacho", b =>
                {
                    b.Property<string>("NroTransporte")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("NroCompartimento")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<decimal?>("APIDespachado")
                        .HasColumnType("decimal(8,4)");

                    b.Property<DateTime>("FechaCompletado")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Temperatura")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("Vol60")
                        .HasColumnType("decimal(16,2)");

                    b.Property<decimal?>("VolObservado")
                        .HasColumnType("decimal(16,2)");

                    b.HasKey("NroTransporte", "NroCompartimento");

                    b.ToTable("confirmacion_despacho", (string)null);
                });

            modelBuilder.Entity("Despachos.Api.Models.DespachoDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("API")
                        .HasColumnType("decimal(8,4)");

                    b.Property<string>("CustomerCode")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Destinatario")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<string>("NroCompartimento")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("NroEntrega")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("NroTransporte")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)");

                    b.Property<string>("SCOP")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UMVol")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<decimal>("Volumen")
                        .HasColumnType("decimal(16,2)");

                    b.HasKey("Id");

                    b.HasIndex("NroTransporte", "NroCompartimento")
                        .IsUnique();

                    b.ToTable("despachos_detail", (string)null);
                });

            modelBuilder.Entity("Despachos.Api.Models.DespachoHeader", b =>
                {
                    b.Property<string>("NroTransporte")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("BayQueuePriority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("date");

                    b.Property<string>("IndViaje")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Mayorista")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PlacaVeh")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("Terminal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("NroTransporte");

                    b.HasIndex("Estado");

                    b.ToTable("despachos_header", (string)null);
                });

            modelBuilder.Entity("Despachos.Api.Models.OutboxConfirmacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<int>("MaxReintentos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<string>("NroTransporte")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ProximoIntentoEn")
                        .HasColumnType("datetime");

                    b.Property<int>("Reintentos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UltimoIntentoEn")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("NroTransporte")
                        .IsUnique();

                    b.HasIndex("Estado", "CreadoEn");

                    b.ToTable("outbox_confirmacion", (string)null);
                });

            modelBuilder.Entity("Despachos.Api.Models.DespachoDetail", b =>
                {
                    b.HasOne("Despachos.Api.Models.DespachoHeader", "Header")
                        .WithMany("Details")
                        .HasForeignKey("NroTransporte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Header");
                });

            modelBuilder.Entity("Despachos.Api.Models.DespachoHeader", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
