//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Despachos.Api.SoapSap
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:petroperu.com.pe:pmerp:tas:Confirma_Carga", ConfigurationName="Despachos.Api.SoapSap.SIS_Confirma_Carga")]
    public interface SIS_Confirma_Carga
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Despachos.Api.SoapSap.SIS_Confirma_CargaResponse SIS_Confirma_Carga(Despachos.Api.SoapSap.SIS_Confirma_CargaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<Despachos.Api.SoapSap.SIS_Confirma_CargaResponse> SIS_Confirma_CargaAsync(Despachos.Api.SoapSap.SIS_Confirma_CargaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:petroperu.com.pe:pmerp:tas:Confirma_Carga")]
    public partial class DT_Confirma_Carga_Request
    {
        
        private string i_NRO_TRANSPORTEField;
        
        private DT_Confirma_Carga_DetItem[][] detalleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string I_NRO_TRANSPORTE
        {
            get
            {
                return this.i_NRO_TRANSPORTEField;
            }
            set
            {
                this.i_NRO_TRANSPORTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", typeof(DT_Confirma_Carga_DetItem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_Confirma_Carga_DetItem[][] Detalle
        {
            get
            {
                return this.detalleField;
            }
            set
            {
                this.detalleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:petroperu.com.pe:pmerp:tas:Confirma_Carga")]
    public partial class DT_Confirma_Carga_DetItem
    {
        
        private string nRO_TRANSField;
        
        private string nRO_ENTREGAField;
        
        private string cOMPARTIMENTOField;
        
        private string pROD_COMERField;
        
        private string t_DESPACHOField;
        
        private string aPI_DESPACHOField;
        
        private string vOL_DESPA_OBSField;
        
        private string uMVOLField;
        
        private string vOL_DESPA_60Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NRO_TRANS
        {
            get
            {
                return this.nRO_TRANSField;
            }
            set
            {
                this.nRO_TRANSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string NRO_ENTREGA
        {
            get
            {
                return this.nRO_ENTREGAField;
            }
            set
            {
                this.nRO_ENTREGAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string COMPARTIMENTO
        {
            get
            {
                return this.cOMPARTIMENTOField;
            }
            set
            {
                this.cOMPARTIMENTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string PROD_COMER
        {
            get
            {
                return this.pROD_COMERField;
            }
            set
            {
                this.pROD_COMERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string T_DESPACHO
        {
            get
            {
                return this.t_DESPACHOField;
            }
            set
            {
                this.t_DESPACHOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string API_DESPACHO
        {
            get
            {
                return this.aPI_DESPACHOField;
            }
            set
            {
                this.aPI_DESPACHOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string VOL_DESPA_OBS
        {
            get
            {
                return this.vOL_DESPA_OBSField;
            }
            set
            {
                this.vOL_DESPA_OBSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string UMVOL
        {
            get
            {
                return this.uMVOLField;
            }
            set
            {
                this.uMVOLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string VOL_DESPA_60
        {
            get
            {
                return this.vOL_DESPA_60Field;
            }
            set
            {
                this.vOL_DESPA_60Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:petroperu.com.pe:pmerp:tas:Confirma_Carga")]
    public partial class DT_RETURN
    {
        
        private string tYPEField;
        
        private string idField;
        
        private string nUMBERField;
        
        private string mESSAGEField;
        
        private string lOG_NOField;
        
        private string lOG_MSG_NOField;
        
        private string mESSAGE_V1Field;
        
        private string mESSAGE_V2Field;
        
        private string mESSAGE_V3Field;
        
        private string mESSAGE_V4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE
        {
            get
            {
                return this.tYPEField;
            }
            set
            {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NUMBER
        {
            get
            {
                return this.nUMBERField;
            }
            set
            {
                this.nUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MESSAGE
        {
            get
            {
                return this.mESSAGEField;
            }
            set
            {
                this.mESSAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LOG_NO
        {
            get
            {
                return this.lOG_NOField;
            }
            set
            {
                this.lOG_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LOG_MSG_NO
        {
            get
            {
                return this.lOG_MSG_NOField;
            }
            set
            {
                this.lOG_MSG_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MESSAGE_V1
        {
            get
            {
                return this.mESSAGE_V1Field;
            }
            set
            {
                this.mESSAGE_V1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MESSAGE_V2
        {
            get
            {
                return this.mESSAGE_V2Field;
            }
            set
            {
                this.mESSAGE_V2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MESSAGE_V3
        {
            get
            {
                return this.mESSAGE_V3Field;
            }
            set
            {
                this.mESSAGE_V3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MESSAGE_V4
        {
            get
            {
                return this.mESSAGE_V4Field;
            }
            set
            {
                this.mESSAGE_V4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:petroperu.com.pe:pmerp:tas:Confirma_Carga")]
    public partial class DT_Confirma_Carga_Response
    {
        
        private DT_RETURN returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_RETURN Return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SIS_Confirma_CargaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:petroperu.com.pe:pmerp:tas:Confirma_Carga", Order=0)]
        public Despachos.Api.SoapSap.DT_Confirma_Carga_Request MT_Confirma_Carga_Request;
        
        public SIS_Confirma_CargaRequest()
        {
        }
        
        public SIS_Confirma_CargaRequest(Despachos.Api.SoapSap.DT_Confirma_Carga_Request MT_Confirma_Carga_Request)
        {
            this.MT_Confirma_Carga_Request = MT_Confirma_Carga_Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SIS_Confirma_CargaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:petroperu.com.pe:pmerp:tas:Confirma_Carga", Order=0)]
        public Despachos.Api.SoapSap.DT_Confirma_Carga_Response MT_Confirma_Carga_Response;
        
        public SIS_Confirma_CargaResponse()
        {
        }
        
        public SIS_Confirma_CargaResponse(Despachos.Api.SoapSap.DT_Confirma_Carga_Response MT_Confirma_Carga_Response)
        {
            this.MT_Confirma_Carga_Response = MT_Confirma_Carga_Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface SIS_Confirma_CargaChannel : Despachos.Api.SoapSap.SIS_Confirma_Carga, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class SIS_Confirma_CargaClient : System.ServiceModel.ClientBase<Despachos.Api.SoapSap.SIS_Confirma_Carga>, Despachos.Api.SoapSap.SIS_Confirma_Carga
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SIS_Confirma_CargaClient(EndpointConfiguration endpointConfiguration) : 
                base(SIS_Confirma_CargaClient.GetBindingForEndpoint(endpointConfiguration), SIS_Confirma_CargaClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SIS_Confirma_CargaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SIS_Confirma_CargaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SIS_Confirma_CargaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SIS_Confirma_CargaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SIS_Confirma_CargaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Despachos.Api.SoapSap.SIS_Confirma_CargaResponse SIS_Confirma_Carga(Despachos.Api.SoapSap.SIS_Confirma_CargaRequest request)
        {
            return base.Channel.SIS_Confirma_Carga(request);
        }
        
        public System.Threading.Tasks.Task<Despachos.Api.SoapSap.SIS_Confirma_CargaResponse> SIS_Confirma_CargaAsync(Despachos.Api.SoapSap.SIS_Confirma_CargaRequest request)
        {
            return base.Channel.SIS_Confirma_CargaAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://petpidqc.petroperu.com.pe:51200/XISOAPAdapter/MessageServlet?senderParty=&" +
                        "senderService=BC_WS&receiverParty=&receiverService=&interface=SIS_Confirma_Carga" +
                        "&interfaceNamespace=urn%3Apetroperu.com.pe%3Apmerp%3Atas%3AConfirma_Carga");
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                return new System.ServiceModel.EndpointAddress("https://petpidqc.petroperu.com.pe:51201/XISOAPAdapter/MessageServlet?senderParty=" +
                        "&senderService=BC_WS&receiverParty=&receiverService=&interface=SIS_Confirma_Carg" +
                        "a&interfaceNamespace=urn%3Apetroperu.com.pe%3Apmerp%3Atas%3AConfirma_Carga");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            HTTP_Port,
            
            HTTPS_Port,
        }
    }
}
